-- begin UNILEVERPLANTAS_ORDEN
alter table UNILEVERPLANTAS_ORDEN add constraint FK_UNILEVERPLANTAS_ORDEN_ON_CLIENTE foreign key (CLIENTE_ID) references UNILEVERPLANTAS_CLIENTES(ID)^
create index IDX_UNILEVERPLANTAS_ORDEN_ON_CLIENTE on UNILEVERPLANTAS_ORDEN (CLIENTE_ID)^
-- end UNILEVERPLANTAS_ORDEN
-- begin UNILEVERPLANTAS_ORDEN_LINEA
alter table UNILEVERPLANTAS_ORDEN_LINEA add constraint FK_UNILEVERPLANTAS_ORDEN_LINEA_ON_ORDEN foreign key (ORDEN_ID) references UNILEVERPLANTAS_ORDEN(ID)^
alter table UNILEVERPLANTAS_ORDEN_LINEA add constraint FK_UNILEVERPLANTAS_ORDEN_LINEA_ON_PRODUCTO foreign key (PRODUCTO_ID) references UNILEVERPLANTAS_PRODUCTO(ID)^
create index IDX_UNILEVERPLANTAS_ORDEN_LINEA_ON_ORDEN on UNILEVERPLANTAS_ORDEN_LINEA (ORDEN_ID)^
create index IDX_UNILEVERPLANTAS_ORDEN_LINEA_ON_PRODUCTO on UNILEVERPLANTAS_ORDEN_LINEA (PRODUCTO_ID)^
-- end UNILEVERPLANTAS_ORDEN_LINEA
